apps/accounts/urls.py
from django.urls import path
from .views import SetSpecial

app_name = "account"

urlpatterns = [
    path("set-special/",SetSpecial.as_view(),name="set-special")
]

apps/file/urls.py
from django.urls import path
from .views import FileList, AddFile, DetailFile, FileDownload, DeleteFile

app_name = "file"

urlpatterns = [
    path("", FileList.as_view(), name= "file-list"),
    path('add/',AddFile.as_view(),name="add-file"),
    path("detail/<int:id>/<str:slug>/", DetailFile.as_view(), name="file-detail"),
    path("download/<int:id>/<str:slug>/",FileDownload.as_view(),name="download-file"),
    path("delete/<int:id>/<str:slug>/", DeleteFile, name="delete-file")
]

uploader/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path("",include("apps.file.urls")),
    path("user/",include("apps.accounts.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'accounts.views.handler404'

apps/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>{%block title%}{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
{% include 'base/navbar.html' %}
<div class="container">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
    <br>
<div class="container ">
    <div class="shadow p-4 mb-5 bg-body rounded">
        {%block body%}
        {%endblock%}
    </div>
</div>
</div>
</body>
</html>

apps/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{%url 'file:file-list'%}">Uploader</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{%url 'file:add-file' %}">Add</a>
        {%if request.user.is_special == False%}
          <a class="nav-link" href="{%url 'account:set-special' %}">Special User</a>
        {%endif%}
          <a class="nav-link" href="{%url 'account_logout'%}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'account_signup'%}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'account_login'%}">Login</a>
        </li>
      {% endif %}
      </ul>
    </div>
  </div>
</nav>