apps/file/urls.py
from django.urls import path
from .views import FileList, AddFile, DetailFile, FileDownload, DeleteFile

app_name = "file"

urlpatterns = [
    path("", FileList.as_view(), name= "file-list"),
    path('add/',AddFile.as_view(),name="add-file"),
    path("detail/<int:id>/<str:slug>/", DetailFile.as_view(), name="file-detail"),
    path("download/<int:id>/<str:slug>/",FileDownload.as_view(),name="download-file"),
    path("delete/<int:id>/<str:slug>/", DeleteFile, name="delete-file")
]

uploader/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path("",include("apps.file.urls")),
    path("user/",include("apps.accounts.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'accounts.views.handler404'

apps/file/models.py
from django.db import models
from accounts.models import User

# Create your models here.
class UserFile(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    slug = models.SlugField(blank=True, null=True)
    owner =  models.ForeignKey(User,blank=True,null=True,on_delete=models.SET_NULL)
    file = models.FileField(upload_to="files/%Y-%m-%d")
    views = models.ManyToManyField("IpAddress", blank=True, related_name="hits")
    def __str__(self):
        return self.title

class IpAddress(models.Model):
    ip_address = models.GenericIPAddressField()
    def __str__(self) -> str:
        return self.ip_address

apps/file/forms.py
from django import forms
from file.models import UserFile

class FileForm(forms.ModelForm):
    class Meta:
        model = UserFile
        fields = ("title","description","slug","owner","file")

apps/file/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import View, ListView, DetailView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import FileResponse
from django.utils.text import slugify

from file.models import UserFile
from accounts.models import User
from .forms import FileForm
from .mixins import LimitMixin

class FileList(LoginRequiredMixin, ListView):
    '''A list of all uploaded files from a user'''
    template_name = "file/list.html"
    context_object_name = "files"

    def get_queryset(self):
        object = UserFile.objects.filter(owner= self.request.user)
        return object


class AddFile(LoginRequiredMixin, LimitMixin, FormView):
    '''Add a new file'''
    template_name = "file/add.html"
    form_class = FileForm
    success_url = "file:file-list"

    @transaction.atomic()
    def form_valid(self, form):
        form = self.form_class(self.request.POST, self.request.FILES)
        form = form.save(commit=False)

        form.slug = slugify(form.title)
        form.owner = self.request.user

        if self.request.user.is_special and form.file.size < 10485760:
                self.request.user.limit = self.request.user.limit - 1
                self.request.user.save()
                form.save()
                return redirect(self.success_url)

        if form.file.size < 5242880 :
                self.request.user.limit = self.request.user.limit - 1
                self.request.user.save()
                form.save()
                return redirect(self.success_url)

        return redirect(self.success_url)


class DetailFile(DetailView):
    '''Detail page of a file'''
    template_name = "file/detail.html"

    def get_object(self):
        object = get_object_or_404(UserFile, id=self.kwargs["id"], slug=self.kwargs["slug"])
        ip_address = self.request.user.ip_address
        # add ip to the views
        if ip_address not in object.views.all():
            object.views.add(ip_address)

        return object

# File download view
class FileDownload(View):
    def get(self, request, id, slug, *args, **kwargs):
        object = get_object_or_404(UserFile, id= id, slug=slug)
        return FileResponse(object.file, as_attachment=True)

# File delete view
@transaction.atomic()
def DeleteFile(request, id, slug):
    object = get_object_or_404(UserFile, id= id, slug= slug, owner= request.user)
    object.delete()
    request.user.limit = request.user.limit + 1
    request.user.save()
    return redirect('file:file-list')

apps/templates/file/AddFile.html
{%extends 'base/base.html' %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Add File Page{%endblock%}
</head>
<body>
{%block body%}
<br>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.title|as_crispy_field }}
        <br>
        {{ form.description|as_crispy_field }}
        <br>
        {{ form.file|as_crispy_field }}
        <br>
        <input type="submit" value="Save" class="btn btn-success">
        <br>
</form>
{%endblock%}
</body>
</html>

apps/templates/file/DetailFile.html
{%extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Detail File Page{%endblock%}

</head>
<body>
{%block body%}
<br>
    <h3>Title: {{object.title}}</h3>  <br><hr>
    <h5>Description: {{object.description}}</h5> <br><hr>
    <div>
    <h5>Domain:</h5><p id="demo">{{ request.META.HTTP_HOST }}/detail/{{object.slug}}/</p>
    <input style="width:100px;" class="btn btn-secondary" value="Copy Url" onclick="copy('demo')"/>
    </div>
    <script>
            function copy(element_id){
          var aux = document.createElement("div");
          aux.setAttribute("contentEditable", true);
          aux.innerHTML = document.getElementById(element_id).innerHTML;
          aux.setAttribute("onfocus", "document.execCommand('selectAll',false,null)");
          document.body.appendChild(aux);
          aux.focus();
          document.execCommand("copy");
          document.body.removeChild(aux);}
    </script>
    <hr>
        Download link:   <a href="{% url 'file:download-file' object.slug%}" type="submit" class="btn btn-secondary">Download</a>
    <hr>
    <h6> Viewed by {{object.views.count}} person</h6><hr>
    <h5> Uploaded by: {{object.owner}}</h5><hr>

{%endblock%}
</body>

</html>

apps/templates/file/Home.html
{%extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Home Page{%endblock%}

</head>
<body>
{%block body%}
<br>
<div class="container">
    <div class="shadow p-4 mb-5 bg-body rounded">
        Limit: {{request.user.limit}}/10 <hr>
        {%if object_list.count == 0%}
            <p>you haven't uploaded any file yet...</p>
            <a href="{%url 'file:add-file'%}">Add new file</a>
        {%else%}
            {% for object in object_list %}
                <div class="row align-items-start">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-sm">
                                    Name: {{object.title}}
                                </div>
                                <div class="col-sm">
                                    Slug: {{object.slug}}
                                </div>
                                <div class="col-sm">
                                    <a href="{%url 'file:detail-file' object.slug %}" class="btn btn-secondary">Preview</a>
                                    <a href="{%url 'file:delete-file' object.slug%}" class="btn btn-danger">Delete</a>
                                </div>
                            </div>
                        </li>
                        <br>
                    </ul>
                </div>
                {%endfor%}
            </div>
        {%endif%}


</div>

{%endblock%}
</body>
</html>

apps/templates/file/add.html
{%extends 'base/base.html' %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Add File{%endblock%}
</head>
<body>
{%block body%}

{% if request.user.is_special %}
    <h4>You can upload files less than 10 MBs</h4>
{%else%}
    <h4>You can upload files less than 5 MBs</h4>
{% endif %}

<hr>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.title|as_crispy_field }}
        <br>
        {{ form.description|as_crispy_field }}
        <br>
        {{ form.file|as_crispy_field }}
        <br>
        <input type="submit" value="Save" class="btn btn-success">
        <br>
</form>
{%endblock%}
</body>
</html>

apps/templates/file/detail.html
{%extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}File Detail{%endblock%}

</head>
<body>
{%block body%}
<br>
    <h3>Title: {{object.title}}</h3>  <br><hr>
    <p>Description: {{object.description}}</p><hr>
    <div>
    <h6 style="display: inline;">Address: </h6>
        <p style="display: inline;" id="demo">{{ request.META.HTTP_HOST }}/detail/{{object.id}}/{{object.slug}}/ </p>
    <input style="width:90px; height: 12x;" class="btn btn-secondary" value="Copy Url" onclick="copy('demo')"/>
    </div>
    <script>
            function copy(element_id){
          var aux = document.createElement("div");
          aux.setAttribute("contentEditable", true);
          aux.innerHTML = document.getElementById(element_id).innerHTML;
          aux.setAttribute("onfocus", "document.execCommand('selectAll',false,null)");
          document.body.appendChild(aux);
          aux.focus();
          document.execCommand("copy");
          document.body.removeChild(aux);}
    </script>
    <hr>
        Download link:   <a href="{% url 'file:download-file' object.id object.slug%}" style="width: 90px;" type="submit" class="btn btn-secondary">Download</a>
    <hr>
    <h6> Viewed by {{object.views.count}} person</h6><hr>
    <h6> Uploaded by: {{object.owner}}</h6><hr>
{%endblock%}
</body>

</html>

apps/templates/file/list.html
{%extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Home{%endblock%}

</head>
<body>
{%block body%}
<div class="container">
    Limit: {%if request.user.is_special%}
        {{request.user.limit}}/50
    {%else%}
        {{request.user.limit}}/10
    {%endif%}

    <br>Is special: {{request.user.is_special}}

    <br><a href="{%url 'file:add-file' %}">Add file</a>
    <hr>
    {% for file in files %}
    <div class="text-center">
        <div class="row align-items-start">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-sm">
                            Name: {{file.title}}
                        </div>
                        <div class="col-sm">
                            Slug: {{file.slug}}
                        </div>
                        <div class="col-sm">
                            <a href="{%url 'file:file-detail' file.id file.slug %}" class="btn btn-secondary">Preview</a>
                            <a href="{%url 'file:delete-file' file.id file.slug%}" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </li>
                <br>
            </ul>
        </div>
        {% empty %}
        <p>you haven't uploaded any file yet...</p>
        <a href="{%url 'file:add-file'%}">Add new file</a>
    </div>
    {%endfor%}
</div>
<br>
</div>

{%endblock%}
</body>
</html>